"""Add Sponsor model and custom admin page

Revision ID: 2490637e666e
Revises: 28c3289f6d66
Create Date: 2025-06-29 17:09:34.485409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2490637e666e'
down_revision = '28c3289f6d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('website_url', sa.String(length=200), nullable=True),
    sa.Column('logo_filename', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsor')
    # ### end Alembic commands ###
