"""add_site_theme_table

Revision ID: 28c3289f6d66
Revises: f0df347f15ce
Create Date: 2025-06-29 12:35:53.662700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c3289f6d66'
down_revision = 'f0df347f15ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('primary_color', sa.String(length=50), nullable=True),
    sa.Column('secondary_color', sa.String(length=50), nullable=True),
    sa.Column('accent_color', sa.String(length=50), nullable=True),
    sa.Column('font_family', sa.String(length=200), nullable=True),
    sa.Column('layout_type', sa.String(length=50), nullable=True),
    sa.Column('navigation_style', sa.String(length=50), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_theme')
    # ### end Alembic commands ###
