"""Add page link and upcoming flag to Event

Revision ID: 577612dd4af6
Revises: 
Create Date: 2025-06-28 16:42:26.424916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577612dd4af6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_upcoming', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.create_foreign_key('fk_event_page_id', 'page', ['page_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_page_id', type_='foreignkey')
        batch_op.drop_column('is_upcoming')
        batch_op.drop_column('page_id')

    # ### end Alembic commands ###
